### ISSUE TITLE
Noted in StackOverflow

### ISSUE THREAD

**Issue by thoppe** [Pent00/YenKSP#1]
I've cited your code in an answer in StackOverflow:

http://stackoverflow.com/questions/15878204/k-shortest-paths-implementation-in-igraph-networkx-yens-algorithm/15881138#15881138

There is no licence for the code, so please let me know if this is OK. If you intend to do so, you should mark that the project is open source in the README.

**Comment by kmsquire** [comment]
@Pent00, not sure if you're still watching this project.  Just wondering under what terms/license this code can be used?  

Without a license, technically, anyone who uses this code is in breach of your copyright, although you seem to be okay with it.  (See, e.g., http://www.infoworld.com/article/2615869/open-source-software/github-needs-to-take-open-source-seriously.html)

Would you be willing to add a license?  If you don't care how this code is used, the [MIT license](http://opensource.org/licenses/MIT) is popular.  Otherwise, GPL3 is probably the way to go.

Cheers!

**Comment by kmsquire** [comment]
Bump

**Comment by kmsquire** [comment]
Whoops, just noticed that the files themselves say GPL2.  There should probably be a License.txt file as well, but other than that, you can ignore my question.  Cheers!
